const categories = [
    {
      id: 1,
      title: "Rice",
      description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
      price: "600",
      image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
      category: "Popular",
    },
  
    {
      id: 2,
      title: "Beans",
      description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
      price: "800",
      image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
      category: "Popular",
    },
    {
        id: 3,
        title: "Garri",
        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
        price: "900",
        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
        category: "Popular",
      },
      {
        id: 4,
        title: "Yam",
        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
        price: "300",
        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
        category: "Popular",
      },
      {
        id: 5,
        title: "Potato",
        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
        price: "600",
        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
        category: "Popular",
      },
    
      {
        id: 6,
        title: "Egg",
        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
        price: "800",
        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
        category: "Beverages",
      },
      {
          id: 7,
          title: "Milk",
          description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
          price: "900",
          image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
          category: "Beverages",
        },
        {
          id: 8,
          title: "Milo",
          description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
          price: "300",
          image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
          category: "Beverages",
        },
        {
            id: 9,
            title: "Tomato paste",
            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
            price: "600",
            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
            category: "Groceries",
          },
        
          {
            id: 10,
            title: "Vegetable Oil",
            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
            price: "800",
            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
            category: "Groceries",
          },
          {
              id: 11,
              title: "Palm oil",
              description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
              price: "900",
              image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
              category: "Groceries",
            },
            {
              id: 12,
              title: "Butter",
              description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
              price: "300",
              image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
              category: "Groceries",
            },
            {
                id: 13,
                title: "Hot pepper",
                description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                price: "600",
                image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
                category: "Groceries",
              },
            
              {
                id: 14,
                title: "Custard",
                description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                price: "800",
                image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                category: "Groceries",
              },
              {
                  id: 15,
                  title: "Golden morn",
                  description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                  price: "900",
                  image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
                  category: "Groceries",
                },
                {
                  id: 16,
                  title: "Sugar",
                  description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                  price: "300",
                  image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                  category: "Groceries",
                },
                {
                    id: 17,
                    title: "Cornflakes",
                    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                    price: "600",
                    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
                    category: "Groceries",
                  },
                
                  {
                    id: 18,
                    title: "Giesha",
                    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                    price: "800",
                    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                    category: "Groceries",
                  },
                  {
                      id: 19,
                      title: "Sardine",
                      description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                      price: "900",
                      image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
                      category: "Groceries",
                    },
                    {
                      id: 20,
                      title: "Spaghetti",
                      description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                      price: "300",
                      image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                      category: "Pasta",
                    },
                    {
                        id: 21,
                        title: "Macaroni",
                        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                        price: "600",
                        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
                        category: "Pasta",
                      },
                    
                      {
                        id: 22,
                        title: "Noodles",
                        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                        price: "800",
                        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                        category: "Pasta",
                      },
                      {
                          id: 23,
                          title: "Spaghetinni",
                          description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                          price: "900",
                          image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
                          category: "Pasta",
                        },
                        {
                          id: 24,
                          title: "Wheat",
                          description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                          price: "300",
                          image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                          category: "Swallow",
                        },
                        {
                            id: 25,
                            title: "Semovita",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Swallow",
                          },
                          {
                            id: 26,
                            title: "Yam Flour",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Swallow",
                          },
                          {
                            id: 27,
                            title: "Bean Powder",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Swallow",
                          },
                          {
                            id: 28,
                            title: "Seasoning",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Spices",
                          },
                          {
                            id: 29,
                            title: "Salt",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Spices",
                          },
                          {
                            id: 30,
                            title: "ginger",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Spices",
                          },
                          {
                            id: 31,
                            title: "garlic",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Spices",
                          },
                          {
                            id: 32,
                            title: "curry",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Spices",
                          },
                          {
                            id: 33,
                            title: "Thyme",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Spices",
                          },
                          {
                            id: 34,
                            title: "Banga",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 35,
                            title: "Egusi",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 36,
                            title: "Efo",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 37,
                            title: "Black soup",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 38,
                            title: "Ogbono",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 39,
                            title: "Okro",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 40,
                            title: "Pepper soup",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Soup",
                          },
                          {
                            id: 41,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Ingredient",
                          },
                          {
                            id: 42,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Ingredient",
                          },
                          {
                            id: 43,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Ingredient",
                          },
                          {
                            id: 44,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Ingredient",
                          },
                          {
                            id: 45,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Packages",
                          },
                          {
                            id: 46,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Packages",
                          },
                          {
                            id: 47,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Packages",
                          },
                          {
                            id: 48,
                            title: "Coming Soon",
                            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                            price: "300",
                            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                            category: "Packages",
                          },
]
module.exports = categories;