const data = [
  {
    id: 1,
    title: "Golden penny - Premium taste",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Pasta",
  },

  {
    id: 2,
    title: "Golden penny - Premium taste",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Pasta",
  },

  {
    id: 3,
    title: "Crown",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Pasta",
  },

  {
    id: 4,
    title: "Crown",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Pasta",
  },

  {
    id: 5,
    title: "Slim Golden penny",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Pasta",
  },

  {
    id: 6,
    title: "Slim Golden penny",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Pasta",
  },

  {
    id: 7,
    title: "Crown",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Pasta",
  },

  {
    id: 8,
    title: "Slim Golden penny",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",

    category: "Pasta",
  },

  {
    id: 9,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Groceries",
  },

  {
    id: 10,
    title: "Golden Penny Noodles",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Groceries",
  },

  {
    id: 11,
    title: "Golden Penny Noodles",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Groceries",
  },

  {
    id: 12,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Groceries",
  },

  {
    id: 13,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Groceries",
  },

  {
    id: 14,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Groceries",
  },

  {
    id: 15,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Groceries",
  },

  {
    id: 16,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Groceries",
  },

  {
    id: 17,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Beverages",
  },

  {
    id: 18,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Beverages",
  },

  {
    id: 19,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Beverages",
  },

  {
    id: 20,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Beverages",
  },

  {
    id: 21,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Beverages",
  },

  {
    id: 22,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Beverages",
  },

  {
    id: 23,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Beverages",
  },

  {
    id: 24,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Beverages",
  },

  {
    id: 25,
    title: "Golden penny; Semo",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Swallow",
  },

  {
    id: 26,
    title: "Golden penny; Semo",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Swallow",
  },

  {
    id: 27,
    title: "Golden penny; Semo",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Swallow",
  },

  {
    id: 28,
    title: "Golden penny; Semo",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Swallow",
  },

  {
    id: 29,
    title: "Golden penny; wheat",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Swallow",
  },

  {
    id: 30,
    title: "Golden penny; wheat",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Swallow",
  },

  {
    id: 31,
    title: "Golden penny; wheat",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Swallow",
  },

  {
    id: 32,
    title: "Golden penny; wheat",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Swallow",
  },

  {
    id: 33,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Oil",
  },

  {
    id: 34,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Oil",
  },

  {
    id: 35,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Oil",
  },

  {
    id: 36,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Oil",
  },

  {
    id: 37,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Oil",
  },

  {
    id: 38,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Oil",
  },

  {
    id: 39,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Oil",
  },

  {
    id: 40,
    title: "Golden Penny Twist",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Oil",
  },
  {
    id: 41,
    title: "Oloyin",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Beans",
  },

  {
    id: 42,
    title: "Oloyin",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Beans",
  },

  {
    id: 43,
    title: "Sokoto",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Beans",
  },

  {
    id: 44,
    title: "Sokoto",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Beans",
  },

  {
    id: 45,
    title: "Drum",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Beans",
  },

  {
    id: 46,
    title: "Drum",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "Beans",
  },

  {
    id: 47,
    title: "Palm oil",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "Beans",
  },

  {
    id: 48,
    title: "Palm oil",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Beans",
  },
  {
    id: 49,
    title: "Dangote",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "SUGAR (smallest size)",
  },

  {
    id: 50,
    title: "Dangote",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SUGAR (smallest size)",
  },
  {
    id: 51,
    title: "Africa King(small seed)",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "RICE(Nigerian)",
  },

  {
    id: 52,
    title: "Africa King(small seed)",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "RICE(Nigerian)",
  },

  {
    id: 53,
    title: "Pretty lady(small seed)",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "RICE(Nigerian)",
  },

  {
    id: 54,
    title: "Pretty lady(small seed)",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "RICE(Nigerian)",
  },
  {
    id: 55,
    title: "oriental",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "NOODLES",
  },

  {
    id: 56,
    title: "oriental",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "NOODLES",
  },

  {
    id: 57,
    title: "Indomie",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "NOODLES",
  },
  {
    id: 58,
    title: "Indomie",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "NOODLES",
  },

  {
    id: 59,
    title: "indomitable",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "NOODLES",
  },
  {
    id: 60,
    title: "indomitable",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "600",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "NOODLES",
  },

  {
    id: 61,
    title: "onions chicken",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
    category: "NOODLES",
  },

  {
    id: 62,
    title: "onions chicken",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "900",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
    category: "NOODLES",
  },

  {
    id: 63,
    title: "Gino; pepper and onions",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 64,
    title: "Gino; pepper and onions",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 65,
    title: "Gino; pepper and onions",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 66,
    title: "Gino; tomato only",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 67,
    title: "Gino; tomato only",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 68,
    title: "Gino; party jollof",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 69,
    title: "Gino; party jollof",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 70,
    title: "Gino; party jollof",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "TOMATO PASTE",
  },
  {
    id: 71,
    title: "Gino",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CURRY",
  },
  {
    id: 72,
    title: "Gino",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CURRY",
  },
  {
    id: 73,
    title: "Tasty cubes",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 74,
    title: "Tasty cubes",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 75,
    title: "Tasty cubes",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 76,
    title: "Maggi",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 77,
    title: "Maggi",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 78,
    title: "Knorr",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 79,
    title: "Knorr",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 80,
    title: "Knorr",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SEASONING CUBE",
  },
  {
    id: 81,
    title: "Titus",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 82,
    title: "Titus",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 83,
    title: "Geisha",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 84,
    title: "Geisha",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 85,
    title: "HOT PEPPER",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 86,
    title: "HOT PEPPER",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 87,
    title: "Mom's pride",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 88,
    title: "Mom's pride",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "CAN FOOD",
  },
  {
    id: 89,
    title: "Mr cheff",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 90,
    title: "Mr cheff",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 91,
    title: "Mr cheff",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 92,
    title: "THYME",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 93,
    title: "THYME",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 94,
    title: "Tiger",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 95,
    title: "Tiger",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 96,
    title: "Tiger",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "SALT",
  },
  {
    id: 97,
    title: "Devon king's",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "VEGETABLE OIL",
  },
  {
    id: 98,
    title: "Devon king's",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "VEGETABLE OIL",
  },
  {
    id: 99,
    title: "MyMy",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "MATCHES",
  },
  {
    id: 100,
    title: "MyMy",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "MATCHES",
  },
  {
    id: 101,
    title: "White Garri",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Garri",
  },
  {
    id: 102,
    title: "White Garri",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Garri",
  },
  {
    id: 103,
    title: "Yellow Garri",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Garri",
  },
  {
    id: 104,
    title: "Yellow Garri",
    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
    price: "800",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/m89yr73ost6kb6blvou4.png",
    category: "Garri",
  },

];

module.exports = data;