const data = [
  {
    id: 1,
    title: "Golden penny - Premium taste",
    description: "Premium taste",
    price: "730",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Popular",
  },

  {
    id: 2,
    title: "Crown",
    description: "100% Yummy",
    price: "679.97",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864927/crown_darxvb.png",
    category: "Popular",
  },
   {
    id: 3,
    title: "Dangote",
    description: "Sweet Delight",
    price: "454.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864926/Dangote_salt_xpo84k.png",
    category: "Popular",
  },
  {
    id: 4,
    title: "indomitable",
    description: "The fastest fast-food",
    price: "5899.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864928/indominate_noodles_ip9f6l.png",
    category: "Popular",
  },
  {
    id: 5,
    title: "Gino pepper and onions",
    description: "Perfect for stew and soup",
    price: "649.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864925/Gino_peper_wtajhw.png",
    category: "Top Sales",
  },
  
  {
    id: 6,
    title: "Titus",
    description: "100% healthy and delicious.",
    price: "747",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864928/titus_kckwcz.png",
    category: "Top Sales",
  },
  {
    id: 7,
    title: "MyMy",
    description: "Every stick counts",
    price: "211",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864927/matches_g4bcgf.png",
    category: "Top Sales",
  },
  {
    id: 8,
    title: "White Garri",
    description: "The bond that joins us together",
    price: "699.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864926/white_garri_sils5r.png",
    category: "Top Sales",
  },
      {
          id: 9,
          title: "Golden Penny Noodles",
          description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
          price: "600",
          image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
          category: "Extra",
        },
      
        {
          id: 10,
          title: "Golden Penny Macaroni",
          description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
          price: "800",
          image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
          category: "Extra",
        },
        {
            id: 11,
            title: "Golden Penny Twist",
            description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
            price: "900",
            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
            category: "Extra",
          },
          // {
          //   id: 12,
          //   title: "Golden Penny Noodles",
          //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
          //   price: "300",
          //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
          //   category: "Extra",
          // },
          {
              id: 13,
              title: "Golden Penny Noodles",
              description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
              price: "600",
              image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
              category: "Extra",
            },
          
            {
              id: 14,
              title: "Golden Penny Macaroni",
              description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
              price: "800",
              image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
              category: "Extra",
            },
            {
                id: 15,
                title: "Golden Penny Twist",
                description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                price: "900",
                image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
                category: "Extra",
              },
              // {
              //   id: 16,
              //   title: "Golden Penny Noodles",
              //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
              //   price: "300",
              //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
              //   category: "Extra",
              // },
              {
                  id: 17,
                  title: "Golden Penny Noodles",
                  description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                  price: "600",
                  image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
                  category: "Extra",
                },
              
                {
                  id: 18,
                  title: "Golden Penny Macaroni",
                  description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                  price: "800",
                  image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                  category: "Extra",
                },
                {
                    id: 19,
                    title: "Golden Penny Twist",
                    description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                    price: "900",
                    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
                    category: "Extra",
                  },
                  // {
                  //   id: 20,
                  //   title: "Golden Penny Noodles",
                  //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                  //   price: "300",
                  //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                  //   category: "Extra",
                  // },
                  {
                      id: 21,
                      title: "Golden Penny Noodles",
                      description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                      price: "600",
                      image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
                      category: "Extra",
                    },
                  
                    {
                      id: 22,
                      title: "Golden Penny Macaroni",
                      description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                      price: "800",
                      image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                      category: "Extra",
                    },
                    {
                        id: 23,
                        title: "Golden Penny Twist",
                        description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                        price: "900",
                        image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/uemknao2yx2yiipqr5it.png",
                        category: "Extra",
                      },
                      // {
                      //   id: 24,
                      //   title: "Golden Penny Noodles",
                      //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                      //   price: "300",
                      //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                      //   category: "Extra",
                      // },
]
module.exports = data;