const data = [
  {
    id: 1,
    title: "Golden penny(pieces)",
    description: "Premium taste",
    price: "730",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
    category: "Popular",
  },

  {
    id: 2,
    title: "Crown(pieces)",
    description: "100% Yummy",
    price: "679.97",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864927/crown_darxvb.png",
    category: "Popular",
  },
   {
    id: 3,
    title: "Dangote 250g(1 sachet)",
    description: "Sweet Delight",
    price: "454.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864926/Dangote_salt_xpo84k.png",
    category: "Popular",
  },
  {
    id: 4,
    title: "indomitable(1 carton)",
    description: "The fastest fast-food",
    price: "5899.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864928/indominate_noodles_ip9f6l.png",
    category: "Popular",
  },
  {
    id: 5,
    title: "Gino pepper and onions(1 roll)",
    description: "Perfect for stew and soup",
    price: "649.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864925/Gino_peper_wtajhw.png",
    category: "Top Sales",
  },
  
  {
    id: 6,
    title: "Titus(1 can)",
    description: "100% healthy and delicious.",
    price: "747",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864928/titus_kckwcz.png",
    category: "Top Sales",
  },
  {
    id: 7,
    title: "MyMy(1 pack)",
    description: "Every stick counts",
    price: "211",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864927/matches_g4bcgf.png",
    category: "Top Sales",
  },
  {
    id: 8,
    title: "White Garri(1 congo)",
    description: "The bond that joins us together",
    price: "699.99",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864926/white_garri_sils5r.png",
    category: "Top Sales",
  },
  {
    id: 9,
    title: "Mr cheff(1 sachet)",
    description: "Queen of your food.",
    price: "150",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864928/salt_sltdxf.png",
    category: "Extra",
  },
      
  {
    id: 10,
    title: "Titus(1 can)",
    description: "100% healthy and delicious.",
    price: "747",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864928/titus_kckwcz.png",
    category: "Extra",
  },
  {
    id: 11,
    title: "Maggi(1 sachet)",
    description: "Timeless Culinary Essence",
    price: "400",
    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864925/maggi_seasoning_fx5tvv.png",
    category: "Extra",
  },
          // {
          //   id: 12,
          //   title: "Golden Penny Noodles",
          //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
          //   price: "300",
          //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
          //   category: "Extra",
          // },
          {
            id: 13,
            title: "Gino(1 roll)",
            description: "The must-add spice!",
            price: "514.97",
            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864924/Gino_curry_ym7i9f.png",
            category: "Extra",
          },
          
          {
            id: 14,
            title: "Gino party jollof(1 roll)",
            description: "Spice up your jollof rice.",
            price: "680",
            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864926/Gino_part_jollof_qbq9ti.png",
            category: "Extra",
          },
          {
            id: 15,
            title: "onions chicken(1 carton)",
            description: "Variety just for you.",
            price: "6299.99",
            image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707901641/onion_chicken_uz95om.png",
            category: "Extra",
          },
              // {
              //   id: 16,
              //   title: "Golden Penny Noodles",
              //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
              //   price: "300",
              //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
              //   category: "Extra",
              // },
              {
                id: 17,
                title: "Pretty lady Rice(1 congo)",
                description: "Made from the finest plantations",
                price: "1999.99",
                image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864926/Pretty_lady_rice_tg2mic.png",
                category: "Extra",
              },
              
              {
                id: 18,
                title: "Drum(1 congo)",
                description: "Nutrient-Packed Legumes",
                price: "1899.99",
                image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707901641/Drumbeans_ejoz2f.png",
                category: "Extra",
              },
              {
                id: 19,
                title: "Palm Oil(1 bottle) 75cl",
                description: "Made from the finest oil plantations",
                price: "1100",
                image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707901641/Palmoil_ty9xwm.png",
                category: "Extra",
              },
                  // {
                  //   id: 20,
                  //   title: "Golden Penny Noodles",
                  //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                  //   price: "300",
                  //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                  //   category: "Extra",
                  // },
                  {
                    id: 21,
                    title: "Golden penny Semo(1kg)",
                    description: "Smooth Indulgence",
                    price: "1449.97",
                    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864925/Golden_penny_semo_fyevzg.png",
                    category: "Extra",
                  },
                  
                  {
                    id: 22,
                    title: "Slim Golden penny(pieces)",
                    description: "Sweet delight and served in minutes",
                    price: "",
                    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055137/dyayctijvjplnsoz1v77.png",
                    category: "Extra",
                  },
                  {
                    id: 23,
                    title: "Honey beans(Ewa Oloyin)(1 congo)",
                    description: "Rich Legumes",
                    price: "1899.99",
                    image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1707864924/oloyin_beans_oxtgor.png",
                    category: "Extra",
                  },
                
                      // {
                      //   id: 24,
                      //   title: "Golden Penny Noodles",
                      //   description: "Lorem ipsum dolor sit amet tetur mattis vel dhc kd.",
                      //   price: "300",
                      //   image:"https://res.cloudinary.com/dxd1j0yzt/image/upload/v1700055138/y3hswtjim8ucs1sktert.png",
                      //   category: "Extra",
                      // },
]
module.exports = data;